// Mock data for the entire dashboard

export const employees = [
  {
    id: "EMP001",
    name: "Alex Carter",
    department: "Engineering",
    role: "Senior Developer",
    contact: "alex.carter@airco.com",
    avatar: "AC",
    status: "Present",
    firstEntry: "08:42 AM",
    lastSeen: "2 min ago",
    location: "Floor 3 – Zone A",
    activity: "Working",
    dwellTime: "4h 18m",
    productivity: 87,
    violations: 0,
    faceTrained: true,
    active: true,
    timeline: [
      { time: "08:42 AM", event: "Entered via Main Gate", camera: "CAM-01" },
      { time: "09:05 AM", event: "Reached Floor 3 – Desk Area", camera: "CAM-08" },
      { time: "10:30 AM", event: "Moved to Conference Room B", camera: "CAM-12" },
      { time: "11:15 AM", event: "Returned to Desk", camera: "CAM-08" },
      { time: "12:30 PM", event: "Cafeteria", camera: "CAM-05" },
      { time: "01:05 PM", event: "Back to Desk", camera: "CAM-08" },
    ],
    movements: ["Main Gate", "Floor 3 – Zone A", "Conference Room B", "Cafeteria"],
    snapshots: 3,
    cameraDwell: [
      { camera: "CAM-01", name: "Main Gate", dwell: "12m" },
      { camera: "CAM-08", name: "Engineering A", dwell: "3h 15m" },
      { camera: "CAM-12", name: "Conference Room B", dwell: "45m" },
      { camera: "CAM-05", name: "Cafeteria", dwell: "35m" },
    ],
    violationDetails: {
      phoneUsage: { detected: false, duration: "0m" },
      idleTime: { detected: false, duration: "0m" },
      restrictedZone: { detected: false, zones: [] },
    },
  },
  {
    id: "EMP002",
    name: "Priya Sharma",
    department: "HR",
    role: "HR Manager",
    contact: "priya.sharma@airco.com",
    avatar: "PS",
    status: "Present",
    firstEntry: "09:01 AM",
    lastSeen: "5 min ago",
    location: "Floor 2 – HR Office",
    activity: "Idle",
    dwellTime: "3h 59m",
    productivity: 62,
    violations: 1,
    faceTrained: true,
    active: true,
    timeline: [
      { time: "09:01 AM", event: "Entered via Main Gate", camera: "CAM-01" },
      { time: "09:20 AM", event: "Floor 2 – HR Office", camera: "CAM-06" },
      { time: "11:00 AM", event: "Meeting Room A", camera: "CAM-11" },
      { time: "11:50 AM", event: "Returned to HR Office", camera: "CAM-06" },
    ],
    movements: ["Main Gate", "Floor 2 – HR Office", "Meeting Room A"],
    snapshots: 2,
    cameraDwell: [
      { camera: "CAM-01", name: "Main Gate", dwell: "8m" },
      { camera: "CAM-06", name: "HR Office", dwell: "3h 10m" },
      { camera: "CAM-11", name: "Meeting Room A", dwell: "50m" },
    ],
    violationDetails: {
      phoneUsage: { detected: false, duration: "0m" },
      idleTime: { detected: true, duration: "45m" },
      restrictedZone: { detected: false, zones: [] },
    },
  },
  {
    id: "EMP003",
    name: "James Liu",
    department: "Finance",
    role: "Financial Analyst",
    contact: "james.liu@airco.com",
    avatar: "JL",
    status: "Present",
    firstEntry: "08:55 AM",
    lastSeen: "1 min ago",
    location: "Floor 1 – Finance",
    activity: "Working",
    dwellTime: "4h 05m",
    productivity: 91,
    violations: 0,
    faceTrained: true,
    active: true,
    timeline: [
      { time: "08:55 AM", event: "Entered via Side Gate", camera: "CAM-02" },
      { time: "09:10 AM", event: "Floor 1 – Finance Desk", camera: "CAM-04" },
    ],
    movements: ["Side Gate", "Floor 1 – Finance"],
    snapshots: 1,
    cameraDwell: [
      { camera: "CAM-02", name: "Side Gate", dwell: "5m" },
      { camera: "CAM-04", name: "Finance Floor", dwell: "4h 00m" },
    ],
    violationDetails: {
      phoneUsage: { detected: false, duration: "0m" },
      idleTime: { detected: false, duration: "0m" },
      restrictedZone: { detected: false, zones: [] },
    },
  },
  {
    id: "EMP004",
    name: "Sara Okonkwo",
    department: "Design",
    role: "UI/UX Designer",
    contact: "sara.o@airco.com",
    avatar: "SO",
    status: "Absent",
    firstEntry: "—",
    lastSeen: "Yesterday",
    location: "—",
    activity: "—",
    dwellTime: "—",
    productivity: 0,
    violations: 0,
    faceTrained: true,
    active: true,
    timeline: [],
    movements: [],
    snapshots: 0,
    cameraDwell: [],
    violationDetails: {
      phoneUsage: { detected: false, duration: "0m" },
      idleTime: { detected: false, duration: "0m" },
      restrictedZone: { detected: false, zones: [] },
    },
  },
  {
    id: "EMP005",
    name: "Mohammed Al-Rashid",
    department: "Security",
    role: "Security Officer",
    contact: "m.alrashid@airco.com",
    avatar: "MA",
    status: "Present",
    firstEntry: "07:30 AM",
    lastSeen: "Just now",
    location: "Main Gate – Zone 0",
    activity: "Moving",
    dwellTime: "5h 30m",
    productivity: 78,
    violations: 0,
    faceTrained: true,
    active: true,
    timeline: [
      { time: "07:30 AM", event: "Started shift at Main Gate", camera: "CAM-01" },
      { time: "09:00 AM", event: "Patrol – Floor 1", camera: "CAM-03" },
      { time: "11:00 AM", event: "Patrol – Floor 2", camera: "CAM-06" },
      { time: "12:00 PM", event: "Back to Main Gate", camera: "CAM-01" },
    ],
    movements: ["Main Gate", "Floor 1", "Floor 2"],
    snapshots: 4,
    cameraDwell: [
      { camera: "CAM-01", name: "Main Gate", dwell: "3h 30m" },
      { camera: "CAM-03", name: "Floor 1 Patrol", dwell: "1h 15m" },
      { camera: "CAM-06", name: "Floor 2 Patrol", dwell: "45m" },
    ],
    violationDetails: {
      phoneUsage: { detected: false, duration: "0m" },
      idleTime: { detected: false, duration: "0m" },
      restrictedZone: { detected: false, zones: [] },
    },
  },
  {
    id: "EMP006",
    name: "Nina Patel",
    department: "Engineering",
    role: "DevOps Engineer",
    contact: "nina.patel@airco.com",
    avatar: "NP",
    status: "Present",
    firstEntry: "09:15 AM",
    lastSeen: "8 min ago",
    location: "Floor 3 – Zone B",
    activity: "Phone",
    dwellTime: "3h 45m",
    productivity: 54,
    violations: 2,
    faceTrained: false,
    active: true,
    timeline: [
      { time: "09:15 AM", event: "Entered via Main Gate", camera: "CAM-01" },
      { time: "09:30 AM", event: "Floor 3 – Zone B", camera: "CAM-09" },
      { time: "10:45 AM", event: "Phone usage detected", camera: "CAM-09" },
      { time: "12:00 PM", event: "Restricted Zone Entry", camera: "CAM-13" },
    ],
    movements: ["Main Gate", "Floor 3 – Zone B", "Restricted Area"],
    snapshots: 5,
    cameraDwell: [
      { camera: "CAM-01", name: "Main Gate", dwell: "10m" },
      { camera: "CAM-09", name: "Engineering B", dwell: "3h 00m" },
      { camera: "CAM-13", name: "Server Room", dwell: "35m" },
    ],
    violationDetails: {
      phoneUsage: { detected: true, duration: "18m" },
      idleTime: { detected: false, duration: "0m" },
      restrictedZone: { detected: true, zones: ["Server Room"] },
    },
  },
  {
    id: "EMP007",
    name: "David Kim",
    department: "Operations",
    role: "Ops Coordinator",
    contact: "d.kim@airco.com",
    avatar: "DK",
    status: "Present",
    firstEntry: "08:30 AM",
    lastSeen: "12 min ago",
    location: "Floor 2 – Ops Room",
    activity: "Working",
    dwellTime: "4h 30m",
    productivity: 83,
    violations: 0,
    faceTrained: true,
    active: true,
    timeline: [
      { time: "08:30 AM", event: "Entered via Main Gate", camera: "CAM-01" },
      { time: "08:50 AM", event: "Floor 2 – Ops Room", camera: "CAM-07" },
    ],
    movements: ["Main Gate", "Floor 2 – Ops Room"],
    snapshots: 2,
    cameraDwell: [
      { camera: "CAM-01", name: "Main Gate", dwell: "8m" },
      { camera: "CAM-07", name: "Ops Room", dwell: "4h 22m" },
    ],
    violationDetails: {
      phoneUsage: { detected: false, duration: "0m" },
      idleTime: { detected: false, duration: "0m" },
      restrictedZone: { detected: false, zones: [] },
    },
  },
  {
    id: "EMP008",
    name: "Laura Mendez",
    department: "Marketing",
    role: "Marketing Lead",
    contact: "l.mendez@airco.com",
    avatar: "LM",
    status: "Absent",
    firstEntry: "—",
    lastSeen: "2 days ago",
    location: "—",
    activity: "—",
    dwellTime: "—",
    productivity: 0,
    violations: 0,
    faceTrained: true,
    active: false,
    timeline: [],
    movements: [],
    snapshots: 0,
    cameraDwell: [],
    violationDetails: {
      phoneUsage: { detected: false, duration: "0m" },
      idleTime: { detected: false, duration: "0m" },
      restrictedZone: { detected: false, zones: [] },
    },
  },
]

export const historicalData = [
  {
    date: "2026-04-01",
    label: "Yesterday",
    summary: {
      present: 7,
      absent: 1,
      lateArrivals: 2,
      avgProductivity: 75,
      activeCameras: 8,
      footfall: 42,
      violations: 4,
    },
    insightQuestions: {
      who: { summary: "7 employees", present: ["Alex Carter", "Priya Sharma", "James Liu", "Mohammed Al-Rashid", "Nina Patel", "David Kim", "Sara Okonkwo"] },
      where: { summary: "6 zones active", zones: ["Floor 3 - Zone A", "Floor 2 - HR", "Floor 1 - Finance", "Main Gate", "Floor 3 - Zone B", "Floor 2 - Ops"] },
      what: { summary: "4 working, 2 idle, 1 phone", working: 4, idle: 2, moving: 0, phone: 1 },
      howLong: { summary: "Avg: 5h 12m", breakdown: { "5+ hours": 3, "4-5 hours": 2, "3-4 hours": 2, "< 3 hours": 0 } },
      violations: { summary: "4 detected", list: [
        { type: "Phone Usage", employee: "Nina Patel", time: "09:30 AM", severity: "medium" },
        { type: "Idle Alert", employee: "Priya Sharma", time: "10:15 AM", severity: "low" },
        { type: "Restricted Zone", employee: "Nina Patel", time: "11:00 AM", severity: "critical" },
        { type: "Late Return", employee: "David Kim", time: "02:15 PM", severity: "low" },
      ]},
    },
    employees: [
      { name: "Alex Carter", firstEntry: "08:30 AM", status: "Present", workTime: "5h 45m", productivity: 89, violations: 0 },
      { name: "Priya Sharma", firstEntry: "08:55 AM", status: "Present", workTime: "4h 30m", productivity: 58, violations: 1 },
      { name: "James Liu", firstEntry: "08:45 AM", status: "Present", workTime: "5h 15m", productivity: 92, violations: 0 },
      { name: "Sara Okonkwo", firstEntry: "09:10 AM", status: "Present", workTime: "4h 00m", productivity: 71, violations: 0 },
      { name: "Mohammed Al-Rashid", firstEntry: "07:00 AM", status: "Present", workTime: "6h 30m", productivity: 82, violations: 0 },
      { name: "Nina Patel", firstEntry: "09:20 AM", status: "Present", workTime: "3h 45m", productivity: 48, violations: 2 },
      { name: "David Kim", firstEntry: "08:25 AM", status: "Present", workTime: "5h 00m", productivity: 78, violations: 1 },
      { name: "Laura Mendez", firstEntry: "—", status: "Absent", workTime: "—", productivity: 0, violations: 0 },
    ],
  },
  {
    date: "2026-03-31",
    label: "Mar 31, 2026",
    summary: {
      present: 6,
      absent: 2,
      lateArrivals: 1,
      avgProductivity: 81,
      activeCameras: 9,
      footfall: 38,
      violations: 2,
    },
    insightQuestions: {
      who: { summary: "6 employees", present: ["Alex Carter", "James Liu", "Mohammed Al-Rashid", "Nina Patel", "David Kim", "Laura Mendez"] },
      where: { summary: "5 zones active", zones: ["Floor 3 - Zone A", "Floor 1 - Finance", "Main Gate", "Floor 3 - Zone B", "Marketing"] },
      what: { summary: "5 working, 1 idle", working: 5, idle: 1, moving: 0, phone: 0 },
      howLong: { summary: "Avg: 5h 45m", breakdown: { "5+ hours": 4, "4-5 hours": 1, "3-4 hours": 1, "< 3 hours": 0 } },
      violations: { summary: "2 detected", list: [
        { type: "Idle Alert", employee: "Nina Patel", time: "11:30 AM", severity: "low" },
        { type: "Late Arrival", employee: "Nina Patel", time: "09:45 AM", severity: "medium" },
      ]},
    },
    employees: [
      { name: "Alex Carter", firstEntry: "08:15 AM", status: "Present", workTime: "6h 00m", productivity: 91, violations: 0 },
      { name: "Priya Sharma", firstEntry: "—", status: "Absent", workTime: "—", productivity: 0, violations: 0 },
      { name: "James Liu", firstEntry: "08:30 AM", status: "Present", workTime: "5h 50m", productivity: 94, violations: 0 },
      { name: "Sara Okonkwo", firstEntry: "—", status: "Absent", workTime: "—", productivity: 0, violations: 0 },
      { name: "Mohammed Al-Rashid", firstEntry: "07:15 AM", status: "Present", workTime: "7h 00m", productivity: 85, violations: 0 },
      { name: "Nina Patel", firstEntry: "09:45 AM", status: "Present", workTime: "3h 30m", productivity: 52, violations: 2 },
      { name: "David Kim", firstEntry: "08:40 AM", status: "Present", workTime: "5h 30m", productivity: 80, violations: 0 },
      { name: "Laura Mendez", firstEntry: "09:00 AM", status: "Present", workTime: "5h 15m", productivity: 84, violations: 0 },
    ],
  },
]

export const cameras = [
  { id: "CAM-01", name: "Main Gate", location: "Ground Floor", status: "live", zone: "Entrance" },
  { id: "CAM-02", name: "Side Gate", location: "Ground Floor", status: "live", zone: "Entrance" },
  { id: "CAM-03", name: "Lobby A", location: "Ground Floor", status: "live", zone: "Common" },
  { id: "CAM-04", name: "Finance Floor", location: "Floor 1", status: "live", zone: "Restricted" },
  { id: "CAM-05", name: "Cafeteria", location: "Floor 1", status: "offline", zone: "Common" },
  { id: "CAM-06", name: "HR Office", location: "Floor 2", status: "live", zone: "Office" },
  { id: "CAM-07", name: "Ops Room", location: "Floor 2", status: "live", zone: "Office" },
  { id: "CAM-08", name: "Engineering A", location: "Floor 3", status: "live", zone: "Office" },
  { id: "CAM-09", name: "Engineering B", location: "Floor 3", status: "live", zone: "Office" },
]

export const tickets = [
  {
    id: "TKT-001",
    employee: "Nina Patel",
    employeeId: "EMP006",
    avatar: "NP",
    department: "Engineering",
    type: "Phone Usage",
    severity: "medium",
    time: "10:45 AM",
    camera: "CAM-09 – Engineering B",
    status: "open",
    description: "Employee detected using personal phone for extended period (>5 min) during work hours.",
  },
  {
    id: "TKT-002",
    employee: "Nina Patel",
    employeeId: "EMP006",
    avatar: "NP",
    department: "Engineering",
    type: "Restricted Zone",
    severity: "critical",
    time: "12:00 PM",
    camera: "CAM-13 – Server Room",
    status: "open",
    description: "Unauthorized entry into restricted server room zone detected.",
  },
  {
    id: "TKT-003",
    employee: "Priya Sharma",
    employeeId: "EMP002",
    avatar: "PS",
    department: "HR",
    type: "Idle Alert",
    severity: "low",
    time: "11:30 AM",
    camera: "CAM-06 – HR Office",
    status: "open",
    description: "Employee idle for more than 45 minutes with no detectable activity.",
  },
  {
    id: "TKT-004",
    employee: "Alex Carter",
    employeeId: "EMP001",
    avatar: "AC",
    department: "Engineering",
    type: "Late Return",
    severity: "low",
    time: "01:45 PM",
    camera: "CAM-08 – Engineering A",
    status: "resolved",
    description: "Employee returned from lunch break 15 minutes late.",
  },
  {
    id: "TKT-005",
    employee: "James Liu",
    employeeId: "EMP003",
    avatar: "JL",
    department: "Finance",
    type: "Tailgating",
    severity: "medium",
    time: "09:05 AM",
    camera: "CAM-02 – Side Gate",
    status: "resolved",
    description: "Two people detected passing through access control simultaneously.",
  },
]

export const unknownPersons = [
  {
    id: "UNK-001",
    snapshot: "/placeholder.svg",
    status: "Unknown",
    firstSeen: "10:23 AM",
    lastSeen: "10:47 AM",
    location: "Floor 2 – Corridor",
    activity: "Moving",
    dwellTime: "24 min",
    camera: "CAM-06",
    riskLevel: "Medium",
  },
  {
    id: "UNK-002",
    snapshot: "/placeholder.svg",
    status: "Unknown",
    firstSeen: "11:05 AM",
    lastSeen: "11:08 AM",
    location: "Main Gate",
    activity: "Idle",
    dwellTime: "3 min",
    camera: "CAM-01",
    riskLevel: "Low",
  },
  {
    id: "UNK-003",
    snapshot: "/placeholder.svg",
    status: "Unknown",
    firstSeen: "12:30 PM",
    lastSeen: "12:45 PM",
    location: "Server Room",
    activity: "Suspicious",
    dwellTime: "15 min",
    camera: "CAM-13",
    riskLevel: "High",
  },
]

export const cameraDwellAnalysis = [
  { camera: "CAM-01", name: "Main Gate", totalDwell: "12h 45m", mostActive: "Mohammed Al-Rashid", entries: 34 },
  { camera: "CAM-08", name: "Engineering A", totalDwell: "8h 20m", mostActive: "Alex Carter", entries: 12 },
  { camera: "CAM-06", name: "HR Office", totalDwell: "6h 15m", mostActive: "Priya Sharma", entries: 8 },
  { camera: "CAM-09", name: "Engineering B", totalDwell: "5h 30m", mostActive: "Nina Patel", entries: 9 },
  { camera: "CAM-07", name: "Ops Room", totalDwell: "4h 45m", mostActive: "David Kim", entries: 7 },
  { camera: "CAM-04", name: "Finance Floor", totalDwell: "4h 10m", mostActive: "James Liu", entries: 6 },
]

export const yesterdaySummary = {
  totalEmployees: 7,
  avgWorkHours: "6h 42m",
  violations: 4,
  attendance: 88,
}

export const aiInsightsData = {
  topPerformer: { name: "James Liu", score: 91, streak: 5 },
  bestAttendance: { name: "Mohammed Al-Rashid", days: 30, percentage: 100 },
  lateBehavior: { name: "Nina Patel", times: 3, trend: "increasing" },
  lowWorkHours: { name: "Sara Okonkwo", avgHours: "4h 12m", status: "warning" },
}

export const performanceLeaderboard = [
  { rank: 1, name: "James Liu", department: "Finance", attendance: 100, hours: "6h 45m", score: 95, badge: "gold" },
  { rank: 2, name: "Alex Carter", department: "Engineering", attendance: 97, hours: "6h 30m", score: 91, badge: "silver" },
  { rank: 3, name: "Mohammed Al-Rashid", department: "Security", attendance: 100, hours: "7h 15m", score: 89, badge: "bronze" },
  { rank: 4, name: "David Kim", department: "Operations", attendance: 94, hours: "6h 00m", score: 85, badge: null },
  { rank: 5, name: "Priya Sharma", department: "HR", attendance: 91, hours: "5h 45m", score: 78, badge: null },
]

export const timeBehavior = {
  earlyBirds: 2,
  onTime: 4,
  lateComers: 1,
  overtime: 1,
}

export const dailyReport = [
  { employee: "Alex Carter", firstEntry: "08:42 AM", date: "Today", status: "Present", workTime: "4h 18m", entries: 12, confidence: 98, department: "Engineering" },
  { employee: "Priya Sharma", firstEntry: "09:01 AM", date: "Today", status: "Present", workTime: "3h 59m", entries: 8, confidence: 95, department: "HR" },
  { employee: "James Liu", firstEntry: "08:55 AM", date: "Today", status: "Present", workTime: "4h 05m", entries: 6, confidence: 97, department: "Finance" },
  { employee: "Sara Okonkwo", firstEntry: "—", date: "Today", status: "Absent", workTime: "—", entries: 0, confidence: 0, department: "Design" },
  { employee: "Mohammed Al-Rashid", firstEntry: "07:30 AM", date: "Today", status: "Present", workTime: "5h 30m", entries: 24, confidence: 99, department: "Security" },
  { employee: "Nina Patel", firstEntry: "09:15 AM", date: "Today", status: "Present", workTime: "3h 45m", entries: 9, confidence: 93, department: "Engineering" },
  { employee: "David Kim", firstEntry: "08:30 AM", date: "Today", status: "Present", workTime: "4h 30m", entries: 7, confidence: 96, department: "Operations" },
  { employee: "Laura Mendez", firstEntry: "—", date: "Today", status: "Absent", workTime: "—", entries: 0, confidence: 0, department: "Marketing" },
]
